{{ if .Values.pullCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: mottmac-pull-creds
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ .Values.pullCredentials | quote }}
{{ end }}