apiVersion: v1
kind: ServiceAccount
metadata:
  name: mottmac
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ if .Values.pullCredentials }}
imagePullSecrets:
- name: mottmac-pull-creds
{{ end }}
