apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ .Values.dbName }}
spec:
  image: {{ .Values.imageUrl }}
  postgresVersion: {{ .Values.pgVersion }}
  users:
  - name: {{ .Values.user }}
    databases: 
    - {{ .Values.dbName }}
  instances:
    - name: {{ .Values.instanceName }}
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.storage }}
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: {{ .Values.storage }}